### ISSUE TITLE
有小bug

### ISSUE THREAD

**Issue by lixingkai-6688** [yangzongzhuan/RuoYi-Vue-Oracle#11]
1.SysJobLogMapper.xml的38行和41行多写了个params
2.页面手动刷新的时候请求没有token了
感觉这个版本用的人不多啊

**Comment by qianbilili** [comment]
> 1.SysJobLogMapper.xml的38行和41行多写了个params
> 2.页面手动刷新的时候请求没有token了
> 感觉这个版本用的人不多啊

主要下载下来学习一下权限控制方面具体怎么实现的

**Comment by yangzongzhuan** [comment]
多谢提醒，已修改。
