### ISSUE TITLE
sql.vm中存在日期处理错误

### ISSUE THREAD

**Issue by hmxmylove** [yangzongzhuan/RuoYi-Vue-Oracle#2]
sql.vm中存在日期处理错误，Oracle中不能直接插入字符串形式的日期，需要转换，但可以用Sysdate代替当前日期。

`-- 菜单 SQL
insert into sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
values(${table.menuId}, '${functionName}', '3', '1', '${businessName}', '${moduleName}/${businessName}/index', 1, 'C', '0', '0', '${permissionPrefix}:list', '#', 'admin', sysdate, 'ry', sysdate, '${functionName}菜单');

-- 按钮 SQL
insert into sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
values(seq_sys_menu.nextval, '${functionName}查询', ${table.menuId}, '1',  '#', '', 1,  'F', '0',  '0', '${permissionPrefix}:query',        '#', 'admin', sysdate, 'ry', sysdate, '');

insert into sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
values(seq_sys_menu.nextval, '${functionName}新增', ${table.menuId}, '2',  '#', '', 1,  'F', '0',  '0', '${permissionPrefix}:add',          '#', 'admin', sysdate, 'ry', sysdate, '');

insert into sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
values(seq_sys_menu.nextval, '${functionName}修改', ${table.menuId}, '3',  '#', '', 1,  'F', '0',  '0', '${permissionPrefix}:edit',         '#', 'admin', sysdate, 'ry', sysdate, '');

insert into sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
values(seq_sys_menu.nextval, '${functionName}删除', ${table.menuId}, '4',  '#', '', 1,  'F', '0',  '0', '${permissionPrefix}:remove',       '#', 'admin', sysdate, 'ry', sysdate, '');

insert into sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
values(seq_sys_menu.nextval, '${functionName}导出', ${table.menuId}, '5',  '#', '', 1,  'F', '0',  '0', '${permissionPrefix}:export',       '#', 'admin', sysdate, 'ry', sysdate, '');

#if($pkColumn.increment)
-- ${tableName}主键序列
create sequence seq_${tableName}
increment by 1
start with 10
nomaxvalue
nominvalue
cache 20;
#end`

**Comment by yangzongzhuan** [comment]
多谢提醒，已修改。
