### ISSUE TITLE
RuoYi-Vue-Oracle 单机Redis改Redis集群

### ISSUE THREAD

**Issue by LichengWon** [yangzongzhuan/RuoYi-Vue-Oracle#28]
RuoYi-Vue-Oracle如何将单机Redis改为Redis集群，application.yml配置了
redis:
  cluster:
    nodes:
但是报错，Connection refused: localhost/127.0.0.1:6379，为什么还在找本地配置？
是还有哪里的配置或者代码需要改么？官方文档中没有查到RuoYi-Vue-Oracle这个版本需要如何修改

**Comment by yangzongzhuan** [comment]
根据springboot的默认要求配置就好，
