### ISSUE TITLE
 因增加唯一限制条件只返回单条数据带来的异常 mybatis处理 rownum <= 1问题

### ISSUE THREAD

**Issue by sam-yu** [yangzongzhuan/RuoYi-Vue-Oracle#7]
将 rownum <= 1改为 rownum & lt;= 1或者使用<[!CDATA[ … ]]>包围

RuoYi-Vue-Oracle-master\target\classes\mybatis\system\SysUserMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 99; columnNumber: 92; 元素内容必须由格式正确的字符数据或标记组成。

**Comment by yangzongzhuan** [comment]
多谢提醒，已修正。
