### ISSUE TITLE
SysDeptMapper.xml selectNormalChildrenDeptById method  oracle 11.2 error

### ISSUE THREAD

**Issue by wzg1101** [yangzongzhuan/RuoYi-Vue-Oracle#9]
ORACLE VERSION：11.2.0.1.0
demo:
select count(*) from sys_dept where status = 0 and del_flag = '0' and FIND_IN_SET(0, ancestors)
> ORA-00920: invalid relational operator

**Comment by yangzongzhuan** [comment]
请提供复现步骤或截图。
